### ISSUE TITLE
EventDurationSubscription Attribute send email in twice

### ISSUE THREAD

**Issue by minhhoangvn** [elv1s42/NUnitGo#2]
Hi Kosjakov,

Thank you so much for this open source, i have use it for my automation framework but i think it has one issue with EventDurationSubscription Attribute. When i test it with sample code below
`[Test, NunitGoAction, Category("SuccessCategory")]      
        [EventDurationSubscription("event 1", 1, "myemail@outlook.com")]
        public void NoGuidTest()
        {
            NunitGo.EventStarted("event 1");
            try {
                Assert.AreEqual(1, 2);
            }
            catch (AssertionException e)
            {                           
                System.Threading.Thread.Sleep(22000);
                NunitGo.EventFinished("event 1");
                NunitGo.EventStarted("event 2");
            }           
            NunitGo.EventFinished("event 2");
        }`

In first time it send one email for me but when i re-run it with increase delay time for trigger MaxDifference it send email to me in twice time.
![untitled](https://cloud.githubusercontent.com/assets/17515250/14977719/c112d1da-1140-11e6-8d10-1e52c15f084d.png)
Thank

**Comment by elv1s42** [comment]
Hello.
What version of NUnitGo are you using?
Version v2.1.4 is the latest.

**Comment by minhhoangvn** [comment]
Hi Kosjakov,
I have download from your source code, and not sure if it was latest version.

**Comment by elv1s42** [comment]
Hello again. 
Please, try using the latest version from NuGet or set TestGuid for your test.
